name: Trivy Docker Image Scan and Upload Report

on:
  push:
    branches:
      - main  # or any branch you want

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t trivy-docker-image-scan-target:latest .

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: image
          image-ref: trivy-docker-image-scan-target:latest
          format: table
          output: trivy-docker-image-scan-results.txt

      - name: Upload Trivy Scan Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-docker-image-scan-report
          path: trivy-docker-image-scan-results.txt
